/* 
 * Payment Initiation API
 *
 * OpenAPI for Payment Initiation API Specification
 *
 * The version of the OpenAPI document: v3.1.1
 * Contact: ServiceDesk@openbanking.org.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace FinnovationLabs.OpenBanking.Library.Connector.ObModels.PaymentInitiation.V3p1p1.Model
{
    /// <summary>
    /// The authorisation type request from the TPP.
    /// </summary>
    [DataContract]
    public partial class OBAuthorisation1 :  IEquatable<OBAuthorisation1>, IValidatableObject
    {
        /// <summary>
        /// Gets or Sets AuthorisationType
        /// </summary>
        [DataMember(Name="AuthorisationType", EmitDefaultValue=false)]
        public OBExternalAuthorisation1Code AuthorisationType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="OBAuthorisation1" /> class.
        /// </summary>
        [JsonConstructor]
        protected OBAuthorisation1() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="OBAuthorisation1" /> class.
        /// </summary>
        /// <param name="authorisationType">authorisationType (required).</param>
        /// <param name="completionDateTime">Date and time at which the requested authorisation flow must be completed. All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00.</param>
        public OBAuthorisation1(OBExternalAuthorisation1Code authorisationType = default(OBExternalAuthorisation1Code), DateTimeOffset completionDateTime = default(DateTimeOffset))
        {
            this.AuthorisationType = authorisationType;
            this.CompletionDateTime = completionDateTime;
        }
        
        /// <summary>
        /// Date and time at which the requested authorisation flow must be completed. All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
        /// </summary>
        /// <value>Date and time at which the requested authorisation flow must be completed. All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00</value>
        [DataMember(Name="CompletionDateTime", EmitDefaultValue=false)]
        public DateTimeOffset CompletionDateTime { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class OBAuthorisation1 {\n");
            sb.Append("  AuthorisationType: ").Append(AuthorisationType).Append("\n");
            sb.Append("  CompletionDateTime: ").Append(CompletionDateTime).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as OBAuthorisation1);
        }

        /// <summary>
        /// Returns true if OBAuthorisation1 instances are equal
        /// </summary>
        /// <param name="input">Instance of OBAuthorisation1 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OBAuthorisation1 input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AuthorisationType == input.AuthorisationType ||
                    this.AuthorisationType.Equals(input.AuthorisationType)
                ) && 
                (
                    this.CompletionDateTime == input.CompletionDateTime ||
                    (this.CompletionDateTime != null &&
                    this.CompletionDateTime.Equals(input.CompletionDateTime))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = hashCode * 59 + this.AuthorisationType.GetHashCode();
                if (this.CompletionDateTime != null)
                    hashCode = hashCode * 59 + this.CompletionDateTime.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
