/* 
 * Payment Initiation API
 *
 * OpenAPI for Payment Initiation API Specification
 *
 * The version of the OpenAPI document: v3.1.1
 * Contact: ServiceDesk@openbanking.org.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace FinnovationLabs.OpenBanking.Library.Connector.ObModels.PaymentInitiation.V3p1p1.Model
{
    /// <summary>
    /// Specifies the payment context
    /// </summary>
    /// <value>Specifies the payment context</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum OBExternalPaymentContext1Code
    {
        /// <summary>
        /// Enum BillPayment for value: BillPayment
        /// </summary>
        [EnumMember(Value = "BillPayment")]
        BillPayment = 1,

        /// <summary>
        /// Enum EcommerceGoods for value: EcommerceGoods
        /// </summary>
        [EnumMember(Value = "EcommerceGoods")]
        EcommerceGoods = 2,

        /// <summary>
        /// Enum EcommerceServices for value: EcommerceServices
        /// </summary>
        [EnumMember(Value = "EcommerceServices")]
        EcommerceServices = 3,

        /// <summary>
        /// Enum Other for value: Other
        /// </summary>
        [EnumMember(Value = "Other")]
        Other = 4,

        /// <summary>
        /// Enum PartyToParty for value: PartyToParty
        /// </summary>
        [EnumMember(Value = "PartyToParty")]
        PartyToParty = 5

    }

}
