/* 
 * Payment Initiation API
 *
 * Swagger for Payment Initiation API Specification
 *
 * OpenAPI spec version: v3.1.1
 * Contact: ServiceDesk@openbanking.org.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace FinnovationLabs.OpenBanking.Library.Connector.ObModels.PaymentInitiation.V3p1p1.Model
{
    /// <summary>
    /// Specifies the Open Banking service request types.
    /// </summary>
    /// <value>Specifies the Open Banking service request types.</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum OBExternalPermissions2Code
    {
        /// <summary>
        /// Enum Create for value: Create
        /// </summary>
        [EnumMember(Value = "Create")]
        Create = 1

    }

}
