/* 
 * Payment Initiation API
 *
 * Swagger for Payment Initiation API Specification
 *
 * OpenAPI spec version: v3.1.2-RC1
 * Contact: ServiceDesk@openbanking.org.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace FinnovationLabs.OpenBanking.Library.Connector.ObModels.PaymentInitiation.V3p1p2.Model
{
    /// <summary>
    /// The multiple authorisation flow response from the ASPSP.
    /// </summary>
    [DataContract]
    public partial class OBWriteDomesticStandingOrderResponse4DataMultiAuthorisation :  IEquatable<OBWriteDomesticStandingOrderResponse4DataMultiAuthorisation>, IValidatableObject
    {
        /// <summary>
        /// Specifies the status of the authorisation flow in code form.
        /// </summary>
        /// <value>Specifies the status of the authorisation flow in code form.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Authorised for value: Authorised
            /// </summary>
            [EnumMember(Value = "Authorised")]
            Authorised = 1,

            /// <summary>
            /// Enum AwaitingFurtherAuthorisation for value: AwaitingFurtherAuthorisation
            /// </summary>
            [EnumMember(Value = "AwaitingFurtherAuthorisation")]
            AwaitingFurtherAuthorisation = 2,

            /// <summary>
            /// Enum Rejected for value: Rejected
            /// </summary>
            [EnumMember(Value = "Rejected")]
            Rejected = 3

        }

        /// <summary>
        /// Specifies the status of the authorisation flow in code form.
        /// </summary>
        /// <value>Specifies the status of the authorisation flow in code form.</value>
        [DataMember(Name="Status", EmitDefaultValue=false)]
        public StatusEnum Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="OBWriteDomesticStandingOrderResponse4DataMultiAuthorisation" /> class.
        /// </summary>
        [JsonConstructor]
        protected OBWriteDomesticStandingOrderResponse4DataMultiAuthorisation() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="OBWriteDomesticStandingOrderResponse4DataMultiAuthorisation" /> class.
        /// </summary>
        /// <param name="status">Specifies the status of the authorisation flow in code form. (required).</param>
        /// <param name="numberReceived">Number of authorisations received..</param>
        /// <param name="lastUpdateDateTime">Last date and time at the authorisation flow was updated.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00.</param>
        /// <param name="expirationDateTime">Date and time at which the requested authorisation flow must be completed.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00.</param>
        /// <param name="numberRequired">Number of authorisations required for payment order (total required at the start of the multi authorisation journey)..</param>
        public OBWriteDomesticStandingOrderResponse4DataMultiAuthorisation(StatusEnum status = default(StatusEnum), int? numberReceived = default(int?), DateTime? lastUpdateDateTime = default(DateTime?), DateTime? expirationDateTime = default(DateTime?), int? numberRequired = default(int?))
        {
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new InvalidDataException("status is a required property for OBWriteDomesticStandingOrderResponse4DataMultiAuthorisation and cannot be null");
            }
            else
            {
                this.Status = status;
            }
            this.NumberReceived = numberReceived;
            this.LastUpdateDateTime = lastUpdateDateTime;
            this.ExpirationDateTime = expirationDateTime;
            this.NumberRequired = numberRequired;
        }
        

        /// <summary>
        /// Number of authorisations received.
        /// </summary>
        /// <value>Number of authorisations received.</value>
        [DataMember(Name="NumberReceived", EmitDefaultValue=false)]
        public int? NumberReceived { get; set; }

        /// <summary>
        /// Last date and time at the authorisation flow was updated.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
        /// </summary>
        /// <value>Last date and time at the authorisation flow was updated.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00</value>
        [DataMember(Name="LastUpdateDateTime", EmitDefaultValue=false)]
        public DateTime? LastUpdateDateTime { get; set; }

        /// <summary>
        /// Date and time at which the requested authorisation flow must be completed.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
        /// </summary>
        /// <value>Date and time at which the requested authorisation flow must be completed.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00</value>
        [DataMember(Name="ExpirationDateTime", EmitDefaultValue=false)]
        public DateTime? ExpirationDateTime { get; set; }

        /// <summary>
        /// Number of authorisations required for payment order (total required at the start of the multi authorisation journey).
        /// </summary>
        /// <value>Number of authorisations required for payment order (total required at the start of the multi authorisation journey).</value>
        [DataMember(Name="NumberRequired", EmitDefaultValue=false)]
        public int? NumberRequired { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class OBWriteDomesticStandingOrderResponse4DataMultiAuthorisation {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  NumberReceived: ").Append(NumberReceived).Append("\n");
            sb.Append("  LastUpdateDateTime: ").Append(LastUpdateDateTime).Append("\n");
            sb.Append("  ExpirationDateTime: ").Append(ExpirationDateTime).Append("\n");
            sb.Append("  NumberRequired: ").Append(NumberRequired).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as OBWriteDomesticStandingOrderResponse4DataMultiAuthorisation);
        }

        /// <summary>
        /// Returns true if OBWriteDomesticStandingOrderResponse4DataMultiAuthorisation instances are equal
        /// </summary>
        /// <param name="input">Instance of OBWriteDomesticStandingOrderResponse4DataMultiAuthorisation to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OBWriteDomesticStandingOrderResponse4DataMultiAuthorisation input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                ) && 
                (
                    this.NumberReceived == input.NumberReceived ||
                    (this.NumberReceived != null &&
                    this.NumberReceived.Equals(input.NumberReceived))
                ) && 
                (
                    this.LastUpdateDateTime == input.LastUpdateDateTime ||
                    (this.LastUpdateDateTime != null &&
                    this.LastUpdateDateTime.Equals(input.LastUpdateDateTime))
                ) && 
                (
                    this.ExpirationDateTime == input.ExpirationDateTime ||
                    (this.ExpirationDateTime != null &&
                    this.ExpirationDateTime.Equals(input.ExpirationDateTime))
                ) && 
                (
                    this.NumberRequired == input.NumberRequired ||
                    (this.NumberRequired != null &&
                    this.NumberRequired.Equals(input.NumberRequired))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                if (this.NumberReceived != null)
                    hashCode = hashCode * 59 + this.NumberReceived.GetHashCode();
                if (this.LastUpdateDateTime != null)
                    hashCode = hashCode * 59 + this.LastUpdateDateTime.GetHashCode();
                if (this.ExpirationDateTime != null)
                    hashCode = hashCode * 59 + this.ExpirationDateTime.GetHashCode();
                if (this.NumberRequired != null)
                    hashCode = hashCode * 59 + this.NumberRequired.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
