// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace FinnovationLabs.OpenBanking.Library.BankApiModels.UkObRw.V3p1p8.Vrp.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class OBDomesticVRPControlParametersMaximumIndividualAmount
    {
        /// <summary>
        /// Initializes a new instance of the
        /// OBDomesticVRPControlParametersMaximumIndividualAmount class.
        /// </summary>
        public OBDomesticVRPControlParametersMaximumIndividualAmount()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// OBDomesticVRPControlParametersMaximumIndividualAmount class.
        /// </summary>
        /// <param name="amount">^ A number of monetary units specified in an
        /// active currency where the unit of currency is explicit and
        /// compliant with ISO 4217.</param>
        /// <param name="currency">^ A code allocated to a currency by a
        /// Maintenance Agency under an international identification scheme, as
        /// described in the latest edition of the international standard ISO
        /// 4217 "Codes for the representation of currencies and funds".   |
        /// ActiveOrHistoricCurrencyCode</param>
        public OBDomesticVRPControlParametersMaximumIndividualAmount(string amount, string currency)
        {
            Amount = amount;
            Currency = currency;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets ^ A number of monetary units specified in an active
        /// currency where the unit of currency is explicit and compliant with
        /// ISO 4217.
        /// </summary>
        [JsonProperty(PropertyName = "Amount")]
        public string Amount { get; set; }

        /// <summary>
        /// Gets or sets ^ A code allocated to a currency by a Maintenance
        /// Agency under an international identification scheme, as described
        /// in the latest edition of the international standard ISO 4217 "Codes
        /// for the representation of currencies and funds".   |
        /// ActiveOrHistoricCurrencyCode
        /// </summary>
        [JsonProperty(PropertyName = "Currency")]
        public string Currency { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Amount == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Amount");
            }
            if (Currency == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Currency");
            }
        }
    }
}
