// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace FinnovationLabs.OpenBanking.Library.BankApiModels.UkObRw.V3p1p8.Vrp.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for
    /// OBDomesticVRPControlParametersPeriodicLimitsItemPeriodAlignmentEnum.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum OBDomesticVRPControlParametersPeriodicLimitsItemPeriodAlignmentEnum
    {
        [EnumMember(Value = "Consent")]
        Consent,
        [EnumMember(Value = "Calendar")]
        Calendar
    }
    internal static class OBDomesticVRPControlParametersPeriodicLimitsItemPeriodAlignmentEnumEnumExtension
    {
        internal static string ToSerializedValue(this OBDomesticVRPControlParametersPeriodicLimitsItemPeriodAlignmentEnum? value)
        {
            return value == null ? null : ((OBDomesticVRPControlParametersPeriodicLimitsItemPeriodAlignmentEnum)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this OBDomesticVRPControlParametersPeriodicLimitsItemPeriodAlignmentEnum value)
        {
            switch( value )
            {
                case OBDomesticVRPControlParametersPeriodicLimitsItemPeriodAlignmentEnum.Consent:
                    return "Consent";
                case OBDomesticVRPControlParametersPeriodicLimitsItemPeriodAlignmentEnum.Calendar:
                    return "Calendar";
            }
            return null;
        }

        internal static OBDomesticVRPControlParametersPeriodicLimitsItemPeriodAlignmentEnum? ParseOBDomesticVRPControlParametersPeriodicLimitsItemPeriodAlignmentEnum(this string value)
        {
            switch( value )
            {
                case "Consent":
                    return OBDomesticVRPControlParametersPeriodicLimitsItemPeriodAlignmentEnum.Consent;
                case "Calendar":
                    return OBDomesticVRPControlParametersPeriodicLimitsItemPeriodAlignmentEnum.Calendar;
            }
            return null;
        }
    }
}
