// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace FinnovationLabs.OpenBanking.Library.BankApiModels.UkObRw.V3p1p8.Vrp.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for OBDomesticVRPResponseDataStatusEnum.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum OBDomesticVRPResponseDataStatusEnum
    {
        [EnumMember(Value = "AcceptedCreditSettlementCompleted")]
        AcceptedCreditSettlementCompleted,
        [EnumMember(Value = "AcceptedWithoutPosting")]
        AcceptedWithoutPosting,
        [EnumMember(Value = "AcceptedSettlementCompleted")]
        AcceptedSettlementCompleted,
        [EnumMember(Value = "AcceptedSettlementInProcess")]
        AcceptedSettlementInProcess,
        [EnumMember(Value = "Pending")]
        Pending,
        [EnumMember(Value = "Rejected")]
        Rejected
    }
    internal static class OBDomesticVRPResponseDataStatusEnumEnumExtension
    {
        internal static string ToSerializedValue(this OBDomesticVRPResponseDataStatusEnum? value)
        {
            return value == null ? null : ((OBDomesticVRPResponseDataStatusEnum)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this OBDomesticVRPResponseDataStatusEnum value)
        {
            switch( value )
            {
                case OBDomesticVRPResponseDataStatusEnum.AcceptedCreditSettlementCompleted:
                    return "AcceptedCreditSettlementCompleted";
                case OBDomesticVRPResponseDataStatusEnum.AcceptedWithoutPosting:
                    return "AcceptedWithoutPosting";
                case OBDomesticVRPResponseDataStatusEnum.AcceptedSettlementCompleted:
                    return "AcceptedSettlementCompleted";
                case OBDomesticVRPResponseDataStatusEnum.AcceptedSettlementInProcess:
                    return "AcceptedSettlementInProcess";
                case OBDomesticVRPResponseDataStatusEnum.Pending:
                    return "Pending";
                case OBDomesticVRPResponseDataStatusEnum.Rejected:
                    return "Rejected";
            }
            return null;
        }

        internal static OBDomesticVRPResponseDataStatusEnum? ParseOBDomesticVRPResponseDataStatusEnum(this string value)
        {
            switch( value )
            {
                case "AcceptedCreditSettlementCompleted":
                    return OBDomesticVRPResponseDataStatusEnum.AcceptedCreditSettlementCompleted;
                case "AcceptedWithoutPosting":
                    return OBDomesticVRPResponseDataStatusEnum.AcceptedWithoutPosting;
                case "AcceptedSettlementCompleted":
                    return OBDomesticVRPResponseDataStatusEnum.AcceptedSettlementCompleted;
                case "AcceptedSettlementInProcess":
                    return OBDomesticVRPResponseDataStatusEnum.AcceptedSettlementInProcess;
                case "Pending":
                    return OBDomesticVRPResponseDataStatusEnum.Pending;
                case "Rejected":
                    return OBDomesticVRPResponseDataStatusEnum.Rejected;
            }
            return null;
        }
    }
}
