// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace FinnovationLabs.OpenBanking.Library.BankApiModels.UkObRw.V3p1p8.Vrp.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Availaility result, clearly indicating the availability of funds given
    /// the Amount in the request.
    /// </summary>
    public partial class OBPAFundsAvailableResult1
    {
        /// <summary>
        /// Initializes a new instance of the OBPAFundsAvailableResult1 class.
        /// </summary>
        public OBPAFundsAvailableResult1()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the OBPAFundsAvailableResult1 class.
        /// </summary>
        /// <param name="fundsAvailableDateTime">Date and time at which the
        /// funds availability check was generated.</param>
        /// <param name="fundsAvailable">Availaility result, clearly indicating
        /// the availability of funds given the Amount in the request. Possible
        /// values include: 'Available', 'NotAvailable'</param>
        public OBPAFundsAvailableResult1(System.DateTimeOffset fundsAvailableDateTime, OBPAFundsAvailableResult1FundsAvailableEnum fundsAvailable)
        {
            FundsAvailableDateTime = fundsAvailableDateTime;
            FundsAvailable = fundsAvailable;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets date and time at which the funds availability check
        /// was generated.
        /// </summary>
        [JsonProperty(PropertyName = "FundsAvailableDateTime")]
        public System.DateTimeOffset FundsAvailableDateTime { get; set; }

        /// <summary>
        /// Gets or sets availaility result, clearly indicating the
        /// availability of funds given the Amount in the request. Possible
        /// values include: 'Available', 'NotAvailable'
        /// </summary>
        [JsonProperty(PropertyName = "FundsAvailable")]
        public OBPAFundsAvailableResult1FundsAvailableEnum FundsAvailable { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
        }
    }
}
