// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace FinnovationLabs.OpenBanking.Library.BankApiModels.UkObRw.V3p1p8.Vrp.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The OBVRPFundsConfirmationRequest object must be used to request funds
    /// availability for a specific amount in the Debtor Account included in
    /// the VRP consents.
    /// </summary>
    public partial class OBVRPFundsConfirmationRequest
    {
        /// <summary>
        /// Initializes a new instance of the OBVRPFundsConfirmationRequest
        /// class.
        /// </summary>
        public OBVRPFundsConfirmationRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the OBVRPFundsConfirmationRequest
        /// class.
        /// </summary>
        public OBVRPFundsConfirmationRequest(OBVRPFundsConfirmationRequestData data = default(OBVRPFundsConfirmationRequestData))
        {
            Data = data;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Data")]
        public OBVRPFundsConfirmationRequestData Data { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Data != null)
            {
                Data.Validate();
            }
        }
    }
}
