// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace AccountAndTransactionAPISpecification.Models
{
    /// <summary> The Model. </summary>
    internal partial class Model
    {
        /// <summary> Initializes a new instance of Model. </summary>
        internal Model()
        {
        }

        /// <summary> Gets the id. </summary>
        public long? Id { get; }
    }
}
