// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace AccountAndTransactionAPISpecification.Models
{
    /// <summary>
    /// Indicates whether the amount is a credit or a debit. 
    /// Usage: A zero amount is considered to be a credit amount.
    /// </summary>
    public enum OBCreditDebitCode0Enum
    {
        /// <summary> Credit. </summary>
        Credit,
        /// <summary> Debit. </summary>
        Debit
    }
}
