// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using Azure.Core;

namespace AccountAndTransactionAPISpecification.Models
{
    /// <summary> The OBReadDataStatement2. </summary>
    public partial class OBReadDataStatement2
    {
        /// <summary> Initializes a new instance of OBReadDataStatement2. </summary>
        internal OBReadDataStatement2()
        {
            Statement = new ChangeTrackingList<OBStatement2>();
        }

        /// <summary> Initializes a new instance of OBReadDataStatement2. </summary>
        /// <param name="statement"></param>
        internal OBReadDataStatement2(IReadOnlyList<OBStatement2> statement)
        {
            Statement = statement;
        }

        /// <summary> Gets the statement. </summary>
        public IReadOnlyList<OBStatement2> Statement { get; }
    }
}
