// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace FinnovationLabs.OpenBanking.Library.Connector.OpenBankingUk.ReadWriteApi.V3p1p4.PaymentInitiation.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for
    /// OBWriteDomesticScheduledConsentResponse4DataReadRefundAccountEnum.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum OBWriteDomesticScheduledConsentResponse4DataReadRefundAccountEnum
    {
        [EnumMember(Value = "No")]
        No,
        [EnumMember(Value = "Yes")]
        Yes
    }
    internal static class OBWriteDomesticScheduledConsentResponse4DataReadRefundAccountEnumEnumExtension
    {
        internal static string ToSerializedValue(this OBWriteDomesticScheduledConsentResponse4DataReadRefundAccountEnum? value)
        {
            return value == null ? null : ((OBWriteDomesticScheduledConsentResponse4DataReadRefundAccountEnum)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this OBWriteDomesticScheduledConsentResponse4DataReadRefundAccountEnum value)
        {
            switch( value )
            {
                case OBWriteDomesticScheduledConsentResponse4DataReadRefundAccountEnum.No:
                    return "No";
                case OBWriteDomesticScheduledConsentResponse4DataReadRefundAccountEnum.Yes:
                    return "Yes";
            }
            return null;
        }

        internal static OBWriteDomesticScheduledConsentResponse4DataReadRefundAccountEnum? ParseOBWriteDomesticScheduledConsentResponse4DataReadRefundAccountEnum(this string value)
        {
            switch( value )
            {
                case "No":
                    return OBWriteDomesticScheduledConsentResponse4DataReadRefundAccountEnum.No;
                case "Yes":
                    return OBWriteDomesticScheduledConsentResponse4DataReadRefundAccountEnum.Yes;
            }
            return null;
        }
    }
}
