// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace FinnovationLabs.OpenBanking.Library.Connector.OpenBankingUk.ReadWriteApi.V3p1p4.PaymentInitiation.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class OBWriteInternationalStandingOrderResponse6Data
    {
        /// <summary>
        /// Initializes a new instance of the
        /// OBWriteInternationalStandingOrderResponse6Data class.
        /// </summary>
        public OBWriteInternationalStandingOrderResponse6Data()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// OBWriteInternationalStandingOrderResponse6Data class.
        /// </summary>
        /// <param name="internationalStandingOrderId">OB: Unique
        /// identification as assigned by the ASPSP to uniquely identify the
        /// international standing order resource.</param>
        /// <param name="consentId">OB: Unique identification as assigned by
        /// the ASPSP to uniquely identify the consent resource.</param>
        /// <param name="creationDateTime">Date and time at which the resource
        /// was created.All dates in the JSON payloads are represented in ISO
        /// 8601 date-time format.
        /// All date-time fields in responses must include the timezone. An
        /// example is below:
        /// 2017-04-05T10:43:07+00:00</param>
        /// <param name="status">Specifies the status of resource in code form.
        /// Possible values include: 'Cancelled', 'InitiationCompleted',
        /// 'InitiationFailed', 'InitiationPending'</param>
        /// <param name="statusUpdateDateTime">Date and time at which the
        /// resource status was updated.All dates in the JSON payloads are
        /// represented in ISO 8601 date-time format.
        /// All date-time fields in responses must include the timezone. An
        /// example is below:
        /// 2017-04-05T10:43:07+00:00</param>
        /// <param name="initiation">The Initiation payload is sent by the
        /// initiating party to the ASPSP. It is used to request movement of
        /// funds from the debtor account to a creditor for an international
        /// standing order.</param>
        /// <param name="multiAuthorisation">The multiple authorisation flow
        /// response from the ASPSP.</param>
        public OBWriteInternationalStandingOrderResponse6Data(string internationalStandingOrderId, string consentId, System.DateTimeOffset creationDateTime, OBWriteInternationalStandingOrderResponse6DataStatusEnum status, System.DateTimeOffset statusUpdateDateTime, OBWriteInternationalStandingOrderResponse6DataInitiation initiation, OBWriteInternationalStandingOrderResponse6DataRefund refund = default(OBWriteInternationalStandingOrderResponse6DataRefund), IList<OBWriteInternationalStandingOrderResponse6DataChargesItem> charges = default(IList<OBWriteInternationalStandingOrderResponse6DataChargesItem>), OBWriteInternationalStandingOrderResponse6DataMultiAuthorisation multiAuthorisation = default(OBWriteInternationalStandingOrderResponse6DataMultiAuthorisation))
        {
            InternationalStandingOrderId = internationalStandingOrderId;
            ConsentId = consentId;
            CreationDateTime = creationDateTime;
            Status = status;
            StatusUpdateDateTime = statusUpdateDateTime;
            Refund = refund;
            Charges = charges;
            Initiation = initiation;
            MultiAuthorisation = multiAuthorisation;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets OB: Unique identification as assigned by the ASPSP to
        /// uniquely identify the international standing order resource.
        /// </summary>
        [JsonProperty(PropertyName = "InternationalStandingOrderId")]
        public string InternationalStandingOrderId { get; set; }

        /// <summary>
        /// Gets or sets OB: Unique identification as assigned by the ASPSP to
        /// uniquely identify the consent resource.
        /// </summary>
        [JsonProperty(PropertyName = "ConsentId")]
        public string ConsentId { get; set; }

        /// <summary>
        /// Gets or sets date and time at which the resource was created.All
        /// dates in the JSON payloads are represented in ISO 8601 date-time
        /// format.
        /// All date-time fields in responses must include the timezone. An
        /// example is below:
        /// 2017-04-05T10:43:07+00:00
        /// </summary>
        [JsonProperty(PropertyName = "CreationDateTime")]
        public System.DateTimeOffset CreationDateTime { get; set; }

        /// <summary>
        /// Gets or sets specifies the status of resource in code form.
        /// Possible values include: 'Cancelled', 'InitiationCompleted',
        /// 'InitiationFailed', 'InitiationPending'
        /// </summary>
        [JsonProperty(PropertyName = "Status")]
        public OBWriteInternationalStandingOrderResponse6DataStatusEnum Status { get; set; }

        /// <summary>
        /// Gets or sets date and time at which the resource status was
        /// updated.All dates in the JSON payloads are represented in ISO 8601
        /// date-time format.
        /// All date-time fields in responses must include the timezone. An
        /// example is below:
        /// 2017-04-05T10:43:07+00:00
        /// </summary>
        [JsonProperty(PropertyName = "StatusUpdateDateTime")]
        public System.DateTimeOffset StatusUpdateDateTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Refund")]
        public OBWriteInternationalStandingOrderResponse6DataRefund Refund { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Charges")]
        public IList<OBWriteInternationalStandingOrderResponse6DataChargesItem> Charges { get; set; }

        /// <summary>
        /// Gets or sets the Initiation payload is sent by the initiating party
        /// to the ASPSP. It is used to request movement of funds from the
        /// debtor account to a creditor for an international standing order.
        /// </summary>
        [JsonProperty(PropertyName = "Initiation")]
        public OBWriteInternationalStandingOrderResponse6DataInitiation Initiation { get; set; }

        /// <summary>
        /// Gets or sets the multiple authorisation flow response from the
        /// ASPSP.
        /// </summary>
        [JsonProperty(PropertyName = "MultiAuthorisation")]
        public OBWriteInternationalStandingOrderResponse6DataMultiAuthorisation MultiAuthorisation { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (InternationalStandingOrderId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "InternationalStandingOrderId");
            }
            if (ConsentId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ConsentId");
            }
            if (Initiation == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Initiation");
            }
            if (Refund != null)
            {
                Refund.Validate();
            }
            if (Charges != null)
            {
                foreach (var element in Charges)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
            if (Initiation != null)
            {
                Initiation.Validate();
            }
            if (MultiAuthorisation != null)
            {
                MultiAuthorisation.Validate();
            }
        }
    }
}
