// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace FinnovationLabs.OpenBanking.Library.Connector.OpenBankingUk.ReadWriteApi.V3p1p4.PaymentInitiation.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for OBWriteInternationalResponse4DataStatusEnum.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum OBWriteInternationalResponse4DataStatusEnum
    {
        [EnumMember(Value = "AcceptedCreditSettlementCompleted")]
        AcceptedCreditSettlementCompleted,
        [EnumMember(Value = "AcceptedSettlementCompleted")]
        AcceptedSettlementCompleted,
        [EnumMember(Value = "AcceptedSettlementInProcess")]
        AcceptedSettlementInProcess,
        [EnumMember(Value = "AcceptedWithoutPosting")]
        AcceptedWithoutPosting,
        [EnumMember(Value = "Pending")]
        Pending,
        [EnumMember(Value = "Rejected")]
        Rejected
    }
    internal static class OBWriteInternationalResponse4DataStatusEnumEnumExtension
    {
        internal static string ToSerializedValue(this OBWriteInternationalResponse4DataStatusEnum? value)
        {
            return value == null ? null : ((OBWriteInternationalResponse4DataStatusEnum)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this OBWriteInternationalResponse4DataStatusEnum value)
        {
            switch( value )
            {
                case OBWriteInternationalResponse4DataStatusEnum.AcceptedCreditSettlementCompleted:
                    return "AcceptedCreditSettlementCompleted";
                case OBWriteInternationalResponse4DataStatusEnum.AcceptedSettlementCompleted:
                    return "AcceptedSettlementCompleted";
                case OBWriteInternationalResponse4DataStatusEnum.AcceptedSettlementInProcess:
                    return "AcceptedSettlementInProcess";
                case OBWriteInternationalResponse4DataStatusEnum.AcceptedWithoutPosting:
                    return "AcceptedWithoutPosting";
                case OBWriteInternationalResponse4DataStatusEnum.Pending:
                    return "Pending";
                case OBWriteInternationalResponse4DataStatusEnum.Rejected:
                    return "Rejected";
            }
            return null;
        }

        internal static OBWriteInternationalResponse4DataStatusEnum? ParseOBWriteInternationalResponse4DataStatusEnum(this string value)
        {
            switch( value )
            {
                case "AcceptedCreditSettlementCompleted":
                    return OBWriteInternationalResponse4DataStatusEnum.AcceptedCreditSettlementCompleted;
                case "AcceptedSettlementCompleted":
                    return OBWriteInternationalResponse4DataStatusEnum.AcceptedSettlementCompleted;
                case "AcceptedSettlementInProcess":
                    return OBWriteInternationalResponse4DataStatusEnum.AcceptedSettlementInProcess;
                case "AcceptedWithoutPosting":
                    return OBWriteInternationalResponse4DataStatusEnum.AcceptedWithoutPosting;
                case "Pending":
                    return OBWriteInternationalResponse4DataStatusEnum.Pending;
                case "Rejected":
                    return OBWriteInternationalResponse4DataStatusEnum.Rejected;
            }
            return null;
        }
    }
}
