// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace FinnovationLabs.OpenBanking.Library.Connector.OpenBankingUk.ReadWriteApi.V3p1p4.PaymentInitiation.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for
    /// OBWriteDomesticStandingOrderConsentResponse5DataAuthorisationAuthorisationTypeEnum.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum OBWriteDomesticStandingOrderConsentResponse5DataAuthorisationAuthorisationTypeEnum
    {
        [EnumMember(Value = "Any")]
        Any,
        [EnumMember(Value = "Single")]
        Single
    }
    internal static class OBWriteDomesticStandingOrderConsentResponse5DataAuthorisationAuthorisationTypeEnumEnumExtension
    {
        internal static string ToSerializedValue(this OBWriteDomesticStandingOrderConsentResponse5DataAuthorisationAuthorisationTypeEnum? value)
        {
            return value == null ? null : ((OBWriteDomesticStandingOrderConsentResponse5DataAuthorisationAuthorisationTypeEnum)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this OBWriteDomesticStandingOrderConsentResponse5DataAuthorisationAuthorisationTypeEnum value)
        {
            switch( value )
            {
                case OBWriteDomesticStandingOrderConsentResponse5DataAuthorisationAuthorisationTypeEnum.Any:
                    return "Any";
                case OBWriteDomesticStandingOrderConsentResponse5DataAuthorisationAuthorisationTypeEnum.Single:
                    return "Single";
            }
            return null;
        }

        internal static OBWriteDomesticStandingOrderConsentResponse5DataAuthorisationAuthorisationTypeEnum? ParseOBWriteDomesticStandingOrderConsentResponse5DataAuthorisationAuthorisationTypeEnum(this string value)
        {
            switch( value )
            {
                case "Any":
                    return OBWriteDomesticStandingOrderConsentResponse5DataAuthorisationAuthorisationTypeEnum.Any;
                case "Single":
                    return OBWriteDomesticStandingOrderConsentResponse5DataAuthorisationAuthorisationTypeEnum.Single;
            }
            return null;
        }
    }
}
