// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace FinnovationLabs.OpenBanking.Library.Connector.OpenBankingUk.ReadWriteApi.V3p1p4.PaymentInitiation.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for
    /// OBWriteInternationalStandingOrderConsentResponse6DataReadRefundAccountEnum.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum OBWriteInternationalStandingOrderConsentResponse6DataReadRefundAccountEnum
    {
        [EnumMember(Value = "No")]
        No,
        [EnumMember(Value = "Yes")]
        Yes
    }
    internal static class OBWriteInternationalStandingOrderConsentResponse6DataReadRefundAccountEnumEnumExtension
    {
        internal static string ToSerializedValue(this OBWriteInternationalStandingOrderConsentResponse6DataReadRefundAccountEnum? value)
        {
            return value == null ? null : ((OBWriteInternationalStandingOrderConsentResponse6DataReadRefundAccountEnum)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this OBWriteInternationalStandingOrderConsentResponse6DataReadRefundAccountEnum value)
        {
            switch( value )
            {
                case OBWriteInternationalStandingOrderConsentResponse6DataReadRefundAccountEnum.No:
                    return "No";
                case OBWriteInternationalStandingOrderConsentResponse6DataReadRefundAccountEnum.Yes:
                    return "Yes";
            }
            return null;
        }

        internal static OBWriteInternationalStandingOrderConsentResponse6DataReadRefundAccountEnum? ParseOBWriteInternationalStandingOrderConsentResponse6DataReadRefundAccountEnum(this string value)
        {
            switch( value )
            {
                case "No":
                    return OBWriteInternationalStandingOrderConsentResponse6DataReadRefundAccountEnum.No;
                case "Yes":
                    return OBWriteInternationalStandingOrderConsentResponse6DataReadRefundAccountEnum.Yes;
            }
            return null;
        }
    }
}
