// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace FinnovationLabs.OpenBanking.Library.Connector.OBUK.ReadWriteApi.V3p1p4.PaymentInitiation.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for OBWriteDomesticScheduledResponse4DataStatusEnum.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum OBWriteDomesticScheduledResponse4DataStatusEnum
    {
        [EnumMember(Value = "Cancelled")]
        Cancelled,
        [EnumMember(Value = "InitiationCompleted")]
        InitiationCompleted,
        [EnumMember(Value = "InitiationFailed")]
        InitiationFailed,
        [EnumMember(Value = "InitiationPending")]
        InitiationPending
    }
    internal static class OBWriteDomesticScheduledResponse4DataStatusEnumEnumExtension
    {
        internal static string ToSerializedValue(this OBWriteDomesticScheduledResponse4DataStatusEnum? value)
        {
            return value == null ? null : ((OBWriteDomesticScheduledResponse4DataStatusEnum)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this OBWriteDomesticScheduledResponse4DataStatusEnum value)
        {
            switch( value )
            {
                case OBWriteDomesticScheduledResponse4DataStatusEnum.Cancelled:
                    return "Cancelled";
                case OBWriteDomesticScheduledResponse4DataStatusEnum.InitiationCompleted:
                    return "InitiationCompleted";
                case OBWriteDomesticScheduledResponse4DataStatusEnum.InitiationFailed:
                    return "InitiationFailed";
                case OBWriteDomesticScheduledResponse4DataStatusEnum.InitiationPending:
                    return "InitiationPending";
            }
            return null;
        }

        internal static OBWriteDomesticScheduledResponse4DataStatusEnum? ParseOBWriteDomesticScheduledResponse4DataStatusEnum(this string value)
        {
            switch( value )
            {
                case "Cancelled":
                    return OBWriteDomesticScheduledResponse4DataStatusEnum.Cancelled;
                case "InitiationCompleted":
                    return OBWriteDomesticScheduledResponse4DataStatusEnum.InitiationCompleted;
                case "InitiationFailed":
                    return OBWriteDomesticScheduledResponse4DataStatusEnum.InitiationFailed;
                case "InitiationPending":
                    return OBWriteDomesticScheduledResponse4DataStatusEnum.InitiationPending;
            }
            return null;
        }
    }
}
