// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace FinnovationLabs.OpenBanking.Library.Connector.UkRwApi.V3p1p4.PaymentInitiation.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for
    /// OBWriteDomesticConsentResponse4DataAuthorisationAuthorisationTypeEnum.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum OBWriteDomesticConsentResponse4DataAuthorisationAuthorisationTypeEnum
    {
        [EnumMember(Value = "Any")]
        Any,
        [EnumMember(Value = "Single")]
        Single
    }
    internal static class OBWriteDomesticConsentResponse4DataAuthorisationAuthorisationTypeEnumEnumExtension
    {
        internal static string ToSerializedValue(this OBWriteDomesticConsentResponse4DataAuthorisationAuthorisationTypeEnum? value)
        {
            return value == null ? null : ((OBWriteDomesticConsentResponse4DataAuthorisationAuthorisationTypeEnum)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this OBWriteDomesticConsentResponse4DataAuthorisationAuthorisationTypeEnum value)
        {
            switch( value )
            {
                case OBWriteDomesticConsentResponse4DataAuthorisationAuthorisationTypeEnum.Any:
                    return "Any";
                case OBWriteDomesticConsentResponse4DataAuthorisationAuthorisationTypeEnum.Single:
                    return "Single";
            }
            return null;
        }

        internal static OBWriteDomesticConsentResponse4DataAuthorisationAuthorisationTypeEnum? ParseOBWriteDomesticConsentResponse4DataAuthorisationAuthorisationTypeEnum(this string value)
        {
            switch( value )
            {
                case "Any":
                    return OBWriteDomesticConsentResponse4DataAuthorisationAuthorisationTypeEnum.Any;
                case "Single":
                    return OBWriteDomesticConsentResponse4DataAuthorisationAuthorisationTypeEnum.Single;
            }
            return null;
        }
    }
}
