<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AssemblyName>FinnovationLabs.OpenBanking.Library.Connector.Web</AssemblyName>
        <RootNamespace>FinnovationLabs.OpenBanking.Library.Connector.Web</RootNamespace>
        <Copyright>Finnovation Labs Limited and Contributors</Copyright>
        <Company>Finnovation Labs Limited</Company>
        <IsPackable>true</IsPackable>
        <Title>Open Banking Connector (version for web apps)</Title>
        <PackageId>FinnovationLabs.OpenBanking.Library.Connector.Web</PackageId>
        <Version>1.0.0-alpha01</Version>
        <Authors>Finnovation Labs Limited and Contributors</Authors>
        <PackageTags>finnovation;labs;open;banking;connector;payments</PackageTags>
        <Description>
            Open Banking Connector simplifies connections to UK Open Banking APIs by absorbing bank differences, handling bank registrations and tokens, and more.
            Use this version for apps using a .NET Generic Host which are ASP.NET Core web apps.
        </Description>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/finlabsuk/open-banking-connector-csharp</RepositoryUrl>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\OpenBanking.Library.Connector\OpenBanking.Library.Connector.csproj"/>
    </ItemGroup>

    <PropertyGroup>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);1591</NoWarn>
    </PropertyGroup>

</Project>
