// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace FinnovationLabs.OpenBanking.Library.BankApiModels.UkObRw.V3p1p8.Pisp.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for OBWriteDomesticStandingOrderResponse6DataStatusEnum.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum OBWriteDomesticStandingOrderResponse6DataStatusEnum
    {
        [EnumMember(Value = "Cancelled")]
        Cancelled,
        [EnumMember(Value = "InitiationCompleted")]
        InitiationCompleted,
        [EnumMember(Value = "InitiationFailed")]
        InitiationFailed,
        [EnumMember(Value = "InitiationPending")]
        InitiationPending
    }
    internal static class OBWriteDomesticStandingOrderResponse6DataStatusEnumEnumExtension
    {
        internal static string ToSerializedValue(this OBWriteDomesticStandingOrderResponse6DataStatusEnum? value)
        {
            return value == null ? null : ((OBWriteDomesticStandingOrderResponse6DataStatusEnum)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this OBWriteDomesticStandingOrderResponse6DataStatusEnum value)
        {
            switch( value )
            {
                case OBWriteDomesticStandingOrderResponse6DataStatusEnum.Cancelled:
                    return "Cancelled";
                case OBWriteDomesticStandingOrderResponse6DataStatusEnum.InitiationCompleted:
                    return "InitiationCompleted";
                case OBWriteDomesticStandingOrderResponse6DataStatusEnum.InitiationFailed:
                    return "InitiationFailed";
                case OBWriteDomesticStandingOrderResponse6DataStatusEnum.InitiationPending:
                    return "InitiationPending";
            }
            return null;
        }

        internal static OBWriteDomesticStandingOrderResponse6DataStatusEnum? ParseOBWriteDomesticStandingOrderResponse6DataStatusEnum(this string value)
        {
            switch( value )
            {
                case "Cancelled":
                    return OBWriteDomesticStandingOrderResponse6DataStatusEnum.Cancelled;
                case "InitiationCompleted":
                    return OBWriteDomesticStandingOrderResponse6DataStatusEnum.InitiationCompleted;
                case "InitiationFailed":
                    return OBWriteDomesticStandingOrderResponse6DataStatusEnum.InitiationFailed;
                case "InitiationPending":
                    return OBWriteDomesticStandingOrderResponse6DataStatusEnum.InitiationPending;
            }
            return null;
        }
    }
}
