// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace FinnovationLabs.OpenBanking.Library.BankApiModels.UkObRw.V3p1p8.Pisp.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for
    /// OBWriteInternationalConsentResponse6DataInitiationInstructionPriorityEnum.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum OBWriteInternationalConsentResponse6DataInitiationInstructionPriorityEnum
    {
        [EnumMember(Value = "Normal")]
        Normal,
        [EnumMember(Value = "Urgent")]
        Urgent
    }
    internal static class OBWriteInternationalConsentResponse6DataInitiationInstructionPriorityEnumEnumExtension
    {
        internal static string ToSerializedValue(this OBWriteInternationalConsentResponse6DataInitiationInstructionPriorityEnum? value)
        {
            return value == null ? null : ((OBWriteInternationalConsentResponse6DataInitiationInstructionPriorityEnum)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this OBWriteInternationalConsentResponse6DataInitiationInstructionPriorityEnum value)
        {
            switch( value )
            {
                case OBWriteInternationalConsentResponse6DataInitiationInstructionPriorityEnum.Normal:
                    return "Normal";
                case OBWriteInternationalConsentResponse6DataInitiationInstructionPriorityEnum.Urgent:
                    return "Urgent";
            }
            return null;
        }

        internal static OBWriteInternationalConsentResponse6DataInitiationInstructionPriorityEnum? ParseOBWriteInternationalConsentResponse6DataInitiationInstructionPriorityEnum(this string value)
        {
            switch( value )
            {
                case "Normal":
                    return OBWriteInternationalConsentResponse6DataInitiationInstructionPriorityEnum.Normal;
                case "Urgent":
                    return OBWriteInternationalConsentResponse6DataInitiationInstructionPriorityEnum.Urgent;
            }
            return null;
        }
    }
}
