// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace FinnovationLabs.OpenBanking.Library.BankApiModels.UkObRw.V3p1p4.Pisp.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for
    /// OBWriteDomesticConsentResponse4DataReadRefundAccountEnum.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum OBWriteDomesticConsentResponse4DataReadRefundAccountEnum
    {
        [EnumMember(Value = "No")]
        No,
        [EnumMember(Value = "Yes")]
        Yes
    }
    internal static class OBWriteDomesticConsentResponse4DataReadRefundAccountEnumEnumExtension
    {
        internal static string ToSerializedValue(this OBWriteDomesticConsentResponse4DataReadRefundAccountEnum? value)
        {
            return value == null ? null : ((OBWriteDomesticConsentResponse4DataReadRefundAccountEnum)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this OBWriteDomesticConsentResponse4DataReadRefundAccountEnum value)
        {
            switch( value )
            {
                case OBWriteDomesticConsentResponse4DataReadRefundAccountEnum.No:
                    return "No";
                case OBWriteDomesticConsentResponse4DataReadRefundAccountEnum.Yes:
                    return "Yes";
            }
            return null;
        }

        internal static OBWriteDomesticConsentResponse4DataReadRefundAccountEnum? ParseOBWriteDomesticConsentResponse4DataReadRefundAccountEnum(this string value)
        {
            switch( value )
            {
                case "No":
                    return OBWriteDomesticConsentResponse4DataReadRefundAccountEnum.No;
                case "Yes":
                    return OBWriteDomesticConsentResponse4DataReadRefundAccountEnum.Yes;
            }
            return null;
        }
    }
}
