// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace FinnovationLabs.OpenBanking.Library.BankApiModels.UkObRw.V3p1p2.Pisp.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for
    /// OBWriteFileConsent3DataAuthorisationAuthorisationTypeEnum.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum OBWriteFileConsent3DataAuthorisationAuthorisationTypeEnum
    {
        [EnumMember(Value = "Any")]
        Any,
        [EnumMember(Value = "Single")]
        Single
    }
    internal static class OBWriteFileConsent3DataAuthorisationAuthorisationTypeEnumEnumExtension
    {
        internal static string ToSerializedValue(this OBWriteFileConsent3DataAuthorisationAuthorisationTypeEnum? value)
        {
            return value == null ? null : ((OBWriteFileConsent3DataAuthorisationAuthorisationTypeEnum)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this OBWriteFileConsent3DataAuthorisationAuthorisationTypeEnum value)
        {
            switch( value )
            {
                case OBWriteFileConsent3DataAuthorisationAuthorisationTypeEnum.Any:
                    return "Any";
                case OBWriteFileConsent3DataAuthorisationAuthorisationTypeEnum.Single:
                    return "Single";
            }
            return null;
        }

        internal static OBWriteFileConsent3DataAuthorisationAuthorisationTypeEnum? ParseOBWriteFileConsent3DataAuthorisationAuthorisationTypeEnum(this string value)
        {
            switch( value )
            {
                case "Any":
                    return OBWriteFileConsent3DataAuthorisationAuthorisationTypeEnum.Any;
                case "Single":
                    return OBWriteFileConsent3DataAuthorisationAuthorisationTypeEnum.Single;
            }
            return null;
        }
    }
}
