// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace FinnovationLabs.OpenBanking.Library.BankApiModels.UkObRw.V3p1p9.Aisp.Models
{
    internal static partial class OBAccountStatus1CodeEnumExtensions
    {
        public static string ToSerialString(this OBAccountStatus1CodeEnum value) => value switch
        {
            OBAccountStatus1CodeEnum.Deleted => "Deleted",
            OBAccountStatus1CodeEnum.Disabled => "Disabled",
            OBAccountStatus1CodeEnum.Enabled => "Enabled",
            OBAccountStatus1CodeEnum.Pending => "Pending",
            OBAccountStatus1CodeEnum.ProForma => "ProForma",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown OBAccountStatus1CodeEnum value.")
        };

        public static OBAccountStatus1CodeEnum ToOBAccountStatus1CodeEnum(this string value)
        {
            if (string.Equals(value, "Deleted", StringComparison.InvariantCultureIgnoreCase)) return OBAccountStatus1CodeEnum.Deleted;
            if (string.Equals(value, "Disabled", StringComparison.InvariantCultureIgnoreCase)) return OBAccountStatus1CodeEnum.Disabled;
            if (string.Equals(value, "Enabled", StringComparison.InvariantCultureIgnoreCase)) return OBAccountStatus1CodeEnum.Enabled;
            if (string.Equals(value, "Pending", StringComparison.InvariantCultureIgnoreCase)) return OBAccountStatus1CodeEnum.Pending;
            if (string.Equals(value, "ProForma", StringComparison.InvariantCultureIgnoreCase)) return OBAccountStatus1CodeEnum.ProForma;
            throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown OBAccountStatus1CodeEnum value.");
        }
    }
}
