// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace FinnovationLabs.OpenBanking.Library.BankApiModels.UkObRw.V3p1p9.Aisp.Models
{
    /// <summary> Rate type for overdraft fee/charge (where it is charged in terms of a rate rather than an amount). </summary>
    internal enum OBInterestRateType1Code0Enum
    {
        /// <summary> INBB. </summary>
        Inbb,
        /// <summary> INFR. </summary>
        Infr,
        /// <summary> INGR. </summary>
        Ingr,
        /// <summary> INLR. </summary>
        Inlr,
        /// <summary> INNE. </summary>
        Inne,
        /// <summary> INOT. </summary>
        Inot
    }
}
