// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace FinnovationLabs.OpenBanking.Library.BankApiModels.UkObRw.V3p1p9.Aisp.Models
{
    internal static partial class OBTransactionCardInstrument1CardSchemeNameEnumExtensions
    {
        public static string ToSerialString(this OBTransactionCardInstrument1CardSchemeNameEnum value) => value switch
        {
            OBTransactionCardInstrument1CardSchemeNameEnum.AmericanExpress => "AmericanExpress",
            OBTransactionCardInstrument1CardSchemeNameEnum.Diners => "Diners",
            OBTransactionCardInstrument1CardSchemeNameEnum.Discover => "Discover",
            OBTransactionCardInstrument1CardSchemeNameEnum.MasterCard => "MasterCard",
            OBTransactionCardInstrument1CardSchemeNameEnum.Visa => "VISA",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown OBTransactionCardInstrument1CardSchemeNameEnum value.")
        };

        public static OBTransactionCardInstrument1CardSchemeNameEnum ToOBTransactionCardInstrument1CardSchemeNameEnum(this string value)
        {
            if (string.Equals(value, "AmericanExpress", StringComparison.InvariantCultureIgnoreCase)) return OBTransactionCardInstrument1CardSchemeNameEnum.AmericanExpress;
            if (string.Equals(value, "Diners", StringComparison.InvariantCultureIgnoreCase)) return OBTransactionCardInstrument1CardSchemeNameEnum.Diners;
            if (string.Equals(value, "Discover", StringComparison.InvariantCultureIgnoreCase)) return OBTransactionCardInstrument1CardSchemeNameEnum.Discover;
            if (string.Equals(value, "MasterCard", StringComparison.InvariantCultureIgnoreCase)) return OBTransactionCardInstrument1CardSchemeNameEnum.MasterCard;
            if (string.Equals(value, "VISA", StringComparison.InvariantCultureIgnoreCase)) return OBTransactionCardInstrument1CardSchemeNameEnum.Visa;
            throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown OBTransactionCardInstrument1CardSchemeNameEnum value.");
        }
    }
}
