// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace FinnovationLabs.OpenBanking.Library.BankApiModels.UkObRw.V3p1p7.Aisp.Models
{
    /// <summary> Specifies the status of account resource in code form. </summary>
    public enum OBAccountStatus1CodeEnum
    {
        /// <summary> Deleted. </summary>
        Deleted,
        /// <summary> Disabled. </summary>
        Disabled,
        /// <summary> Enabled. </summary>
        Enabled,
        /// <summary> Pending. </summary>
        Pending,
        /// <summary> ProForma. </summary>
        ProForma
    }
}
