// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace FinnovationLabs.OpenBanking.Library.BankApiModels.UkObRw.V3p1p7.Aisp.Models
{
    internal static partial class OBExternalStandingOrderStatus1CodeEnumExtensions
    {
        public static string ToSerialString(this OBExternalStandingOrderStatus1CodeEnum value) => value switch
        {
            OBExternalStandingOrderStatus1CodeEnum.Active => "Active",
            OBExternalStandingOrderStatus1CodeEnum.Inactive => "Inactive",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown OBExternalStandingOrderStatus1CodeEnum value.")
        };

        public static OBExternalStandingOrderStatus1CodeEnum ToOBExternalStandingOrderStatus1CodeEnum(this string value)
        {
            if (string.Equals(value, "Active", StringComparison.InvariantCultureIgnoreCase)) return OBExternalStandingOrderStatus1CodeEnum.Active;
            if (string.Equals(value, "Inactive", StringComparison.InvariantCultureIgnoreCase)) return OBExternalStandingOrderStatus1CodeEnum.Inactive;
            throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown OBExternalStandingOrderStatus1CodeEnum value.");
        }
    }
}
