// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace FinnovationLabs.OpenBanking.Library.BankApiModels.UkObRw.V3p1p6.Pisp.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for
    /// OBWriteInternationalStandingOrderConsentResponse7DataReadRefundAccountEnum.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum OBWriteInternationalStandingOrderConsentResponse7DataReadRefundAccountEnum
    {
        [EnumMember(Value = "No")]
        No,
        [EnumMember(Value = "Yes")]
        Yes
    }
    internal static class OBWriteInternationalStandingOrderConsentResponse7DataReadRefundAccountEnumEnumExtension
    {
        internal static string ToSerializedValue(this OBWriteInternationalStandingOrderConsentResponse7DataReadRefundAccountEnum? value)
        {
            return value == null ? null : ((OBWriteInternationalStandingOrderConsentResponse7DataReadRefundAccountEnum)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this OBWriteInternationalStandingOrderConsentResponse7DataReadRefundAccountEnum value)
        {
            switch( value )
            {
                case OBWriteInternationalStandingOrderConsentResponse7DataReadRefundAccountEnum.No:
                    return "No";
                case OBWriteInternationalStandingOrderConsentResponse7DataReadRefundAccountEnum.Yes:
                    return "Yes";
            }
            return null;
        }

        internal static OBWriteInternationalStandingOrderConsentResponse7DataReadRefundAccountEnum? ParseOBWriteInternationalStandingOrderConsentResponse7DataReadRefundAccountEnum(this string value)
        {
            switch( value )
            {
                case "No":
                    return OBWriteInternationalStandingOrderConsentResponse7DataReadRefundAccountEnum.No;
                case "Yes":
                    return OBWriteInternationalStandingOrderConsentResponse7DataReadRefundAccountEnum.Yes;
            }
            return null;
        }
    }
}
