// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace FinnovationLabs.OpenBanking.Library.BankApiModels.UkObRw.V3p1p6.Pisp.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class OBWriteDomesticScheduledResponse5Data
    {
        /// <summary>
        /// Initializes a new instance of the
        /// OBWriteDomesticScheduledResponse5Data class.
        /// </summary>
        public OBWriteDomesticScheduledResponse5Data()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// OBWriteDomesticScheduledResponse5Data class.
        /// </summary>
        /// <param name="domesticScheduledPaymentId">OB: Unique identification
        /// as assigned by the ASPSP to uniquely identify the domestic schedule
        /// payment resource.</param>
        /// <param name="consentId">OB: Unique identification as assigned by
        /// the ASPSP to uniquely identify the consent resource.</param>
        /// <param name="creationDateTime">Date and time at which the message
        /// was created.All dates in the JSON payloads are represented in ISO
        /// 8601 date-time format.
        /// All date-time fields in responses must include the timezone. An
        /// example is below:
        /// 2017-04-05T10:43:07+00:00</param>
        /// <param name="status">Specifies the status of the payment order
        /// resource. Possible values include: 'Cancelled',
        /// 'InitiationCompleted', 'InitiationFailed',
        /// 'InitiationPending'</param>
        /// <param name="statusUpdateDateTime">Date and time at which the
        /// resource status was updated.All dates in the JSON payloads are
        /// represented in ISO 8601 date-time format.
        /// All date-time fields in responses must include the timezone. An
        /// example is below:
        /// 2017-04-05T10:43:07+00:00</param>
        /// <param name="initiation">The Initiation payload is sent by the
        /// initiating party to the ASPSP. It is used to request movement of
        /// funds from the debtor account to a creditor for a single scheduled
        /// domestic payment.</param>
        /// <param name="expectedExecutionDateTime">Expected execution date and
        /// time for the payment resource.All dates in the JSON payloads are
        /// represented in ISO 8601 date-time format.
        /// All date-time fields in responses must include the timezone. An
        /// example is below:
        /// 2017-04-05T10:43:07+00:00</param>
        /// <param name="expectedSettlementDateTime">Expected settlement date
        /// and time for the payment resource.All dates in the JSON payloads
        /// are represented in ISO 8601 date-time format.
        /// All date-time fields in responses must include the timezone. An
        /// example is below:
        /// 2017-04-05T10:43:07+00:00</param>
        /// <param name="refund">Unambiguous identification of the refund
        /// account to which a refund will be made as a result of the
        /// transaction.</param>
        /// <param name="multiAuthorisation">The multiple authorisation flow
        /// response from the ASPSP.</param>
        public OBWriteDomesticScheduledResponse5Data(string domesticScheduledPaymentId, string consentId, System.DateTimeOffset creationDateTime, OBWriteDomesticScheduledResponse5DataStatusEnum status, System.DateTimeOffset statusUpdateDateTime, OBWriteDomesticScheduledResponse5DataInitiation initiation, System.DateTimeOffset? expectedExecutionDateTime = default(System.DateTimeOffset?), System.DateTimeOffset? expectedSettlementDateTime = default(System.DateTimeOffset?), OBWriteDomesticScheduledResponse5DataRefund refund = default(OBWriteDomesticScheduledResponse5DataRefund), IList<OBWriteDomesticScheduledResponse5DataChargesItem> charges = default(IList<OBWriteDomesticScheduledResponse5DataChargesItem>), OBWriteDomesticScheduledResponse5DataMultiAuthorisation multiAuthorisation = default(OBWriteDomesticScheduledResponse5DataMultiAuthorisation), OBDebtorIdentification1 debtor = default(OBDebtorIdentification1))
        {
            DomesticScheduledPaymentId = domesticScheduledPaymentId;
            ConsentId = consentId;
            CreationDateTime = creationDateTime;
            Status = status;
            StatusUpdateDateTime = statusUpdateDateTime;
            ExpectedExecutionDateTime = expectedExecutionDateTime;
            ExpectedSettlementDateTime = expectedSettlementDateTime;
            Refund = refund;
            Charges = charges;
            Initiation = initiation;
            MultiAuthorisation = multiAuthorisation;
            Debtor = debtor;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets OB: Unique identification as assigned by the ASPSP to
        /// uniquely identify the domestic schedule payment resource.
        /// </summary>
        [JsonProperty(PropertyName = "DomesticScheduledPaymentId")]
        public string DomesticScheduledPaymentId { get; set; }

        /// <summary>
        /// Gets or sets OB: Unique identification as assigned by the ASPSP to
        /// uniquely identify the consent resource.
        /// </summary>
        [JsonProperty(PropertyName = "ConsentId")]
        public string ConsentId { get; set; }

        /// <summary>
        /// Gets or sets date and time at which the message was created.All
        /// dates in the JSON payloads are represented in ISO 8601 date-time
        /// format.
        /// All date-time fields in responses must include the timezone. An
        /// example is below:
        /// 2017-04-05T10:43:07+00:00
        /// </summary>
        [JsonProperty(PropertyName = "CreationDateTime")]
        public System.DateTimeOffset CreationDateTime { get; set; }

        /// <summary>
        /// Gets or sets specifies the status of the payment order resource.
        /// Possible values include: 'Cancelled', 'InitiationCompleted',
        /// 'InitiationFailed', 'InitiationPending'
        /// </summary>
        [JsonProperty(PropertyName = "Status")]
        public OBWriteDomesticScheduledResponse5DataStatusEnum Status { get; set; }

        /// <summary>
        /// Gets or sets date and time at which the resource status was
        /// updated.All dates in the JSON payloads are represented in ISO 8601
        /// date-time format.
        /// All date-time fields in responses must include the timezone. An
        /// example is below:
        /// 2017-04-05T10:43:07+00:00
        /// </summary>
        [JsonProperty(PropertyName = "StatusUpdateDateTime")]
        public System.DateTimeOffset StatusUpdateDateTime { get; set; }

        /// <summary>
        /// Gets or sets expected execution date and time for the payment
        /// resource.All dates in the JSON payloads are represented in ISO 8601
        /// date-time format.
        /// All date-time fields in responses must include the timezone. An
        /// example is below:
        /// 2017-04-05T10:43:07+00:00
        /// </summary>
        [JsonProperty(PropertyName = "ExpectedExecutionDateTime")]
        public System.DateTimeOffset? ExpectedExecutionDateTime { get; set; }

        /// <summary>
        /// Gets or sets expected settlement date and time for the payment
        /// resource.All dates in the JSON payloads are represented in ISO 8601
        /// date-time format.
        /// All date-time fields in responses must include the timezone. An
        /// example is below:
        /// 2017-04-05T10:43:07+00:00
        /// </summary>
        [JsonProperty(PropertyName = "ExpectedSettlementDateTime")]
        public System.DateTimeOffset? ExpectedSettlementDateTime { get; set; }

        /// <summary>
        /// Gets or sets unambiguous identification of the refund account to
        /// which a refund will be made as a result of the transaction.
        /// </summary>
        [JsonProperty(PropertyName = "Refund")]
        public OBWriteDomesticScheduledResponse5DataRefund Refund { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Charges")]
        public IList<OBWriteDomesticScheduledResponse5DataChargesItem> Charges { get; set; }

        /// <summary>
        /// Gets or sets the Initiation payload is sent by the initiating party
        /// to the ASPSP. It is used to request movement of funds from the
        /// debtor account to a creditor for a single scheduled domestic
        /// payment.
        /// </summary>
        [JsonProperty(PropertyName = "Initiation")]
        public OBWriteDomesticScheduledResponse5DataInitiation Initiation { get; set; }

        /// <summary>
        /// Gets or sets the multiple authorisation flow response from the
        /// ASPSP.
        /// </summary>
        [JsonProperty(PropertyName = "MultiAuthorisation")]
        public OBWriteDomesticScheduledResponse5DataMultiAuthorisation MultiAuthorisation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Debtor")]
        public OBDebtorIdentification1 Debtor { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (DomesticScheduledPaymentId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "DomesticScheduledPaymentId");
            }
            if (ConsentId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ConsentId");
            }
            if (Initiation == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Initiation");
            }
            if (Refund != null)
            {
                Refund.Validate();
            }
            if (Charges != null)
            {
                foreach (var element in Charges)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
            if (Initiation != null)
            {
                Initiation.Validate();
            }
            if (MultiAuthorisation != null)
            {
                MultiAuthorisation.Validate();
            }
        }
    }
}
