// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace FinnovationLabs.OpenBanking.Library.BankApiModels.UkObRw.V3p1p11.Aisp.Models
{
    /// <summary> Offer type, in a coded form. </summary>
    public enum OBReadOffer1DataOfferTypeEnum
    {
        /// <summary> BalanceTransfer. </summary>
        BalanceTransfer,
        /// <summary> LimitIncrease. </summary>
        LimitIncrease,
        /// <summary> MoneyTransfer. </summary>
        MoneyTransfer,
        /// <summary> Other. </summary>
        Other,
        /// <summary> PromotionalRate. </summary>
        PromotionalRate
    }
}
