// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace FinnovationLabs.OpenBanking.Library.Connector.OBUK.ReadWriteApi.V3p1p6.PaymentInitiation.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for
    /// OBWriteInternationalConsentResponse6DataExchangeRateInformationRateTypeEnum.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum OBWriteInternationalConsentResponse6DataExchangeRateInformationRateTypeEnum
    {
        [EnumMember(Value = "Actual")]
        Actual,
        [EnumMember(Value = "Agreed")]
        Agreed,
        [EnumMember(Value = "Indicative")]
        Indicative
    }
    internal static class OBWriteInternationalConsentResponse6DataExchangeRateInformationRateTypeEnumEnumExtension
    {
        internal static string ToSerializedValue(this OBWriteInternationalConsentResponse6DataExchangeRateInformationRateTypeEnum? value)
        {
            return value == null ? null : ((OBWriteInternationalConsentResponse6DataExchangeRateInformationRateTypeEnum)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this OBWriteInternationalConsentResponse6DataExchangeRateInformationRateTypeEnum value)
        {
            switch( value )
            {
                case OBWriteInternationalConsentResponse6DataExchangeRateInformationRateTypeEnum.Actual:
                    return "Actual";
                case OBWriteInternationalConsentResponse6DataExchangeRateInformationRateTypeEnum.Agreed:
                    return "Agreed";
                case OBWriteInternationalConsentResponse6DataExchangeRateInformationRateTypeEnum.Indicative:
                    return "Indicative";
            }
            return null;
        }

        internal static OBWriteInternationalConsentResponse6DataExchangeRateInformationRateTypeEnum? ParseOBWriteInternationalConsentResponse6DataExchangeRateInformationRateTypeEnum(this string value)
        {
            switch( value )
            {
                case "Actual":
                    return OBWriteInternationalConsentResponse6DataExchangeRateInformationRateTypeEnum.Actual;
                case "Agreed":
                    return OBWriteInternationalConsentResponse6DataExchangeRateInformationRateTypeEnum.Agreed;
                case "Indicative":
                    return OBWriteInternationalConsentResponse6DataExchangeRateInformationRateTypeEnum.Indicative;
            }
            return null;
        }
    }
}
