// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace FinnovationLabs.OpenBanking.Library.Connector.OBUK.ReadWriteApi.V3p1p2.PaymentInitiation.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for OBWriteDomesticConsentResponse3DataStatusEnum.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum OBWriteDomesticConsentResponse3DataStatusEnum
    {
        [EnumMember(Value = "Authorised")]
        Authorised,
        [EnumMember(Value = "AwaitingAuthorisation")]
        AwaitingAuthorisation,
        [EnumMember(Value = "Consumed")]
        Consumed,
        [EnumMember(Value = "Rejected")]
        Rejected
    }
    internal static class OBWriteDomesticConsentResponse3DataStatusEnumEnumExtension
    {
        internal static string ToSerializedValue(this OBWriteDomesticConsentResponse3DataStatusEnum? value)
        {
            return value == null ? null : ((OBWriteDomesticConsentResponse3DataStatusEnum)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this OBWriteDomesticConsentResponse3DataStatusEnum value)
        {
            switch( value )
            {
                case OBWriteDomesticConsentResponse3DataStatusEnum.Authorised:
                    return "Authorised";
                case OBWriteDomesticConsentResponse3DataStatusEnum.AwaitingAuthorisation:
                    return "AwaitingAuthorisation";
                case OBWriteDomesticConsentResponse3DataStatusEnum.Consumed:
                    return "Consumed";
                case OBWriteDomesticConsentResponse3DataStatusEnum.Rejected:
                    return "Rejected";
            }
            return null;
        }

        internal static OBWriteDomesticConsentResponse3DataStatusEnum? ParseOBWriteDomesticConsentResponse3DataStatusEnum(this string value)
        {
            switch( value )
            {
                case "Authorised":
                    return OBWriteDomesticConsentResponse3DataStatusEnum.Authorised;
                case "AwaitingAuthorisation":
                    return OBWriteDomesticConsentResponse3DataStatusEnum.AwaitingAuthorisation;
                case "Consumed":
                    return OBWriteDomesticConsentResponse3DataStatusEnum.Consumed;
                case "Rejected":
                    return OBWriteDomesticConsentResponse3DataStatusEnum.Rejected;
            }
            return null;
        }
    }
}
