/* 
 * Payment Initiation API
 *
 * Swagger for Payment Initiation API Specification
 *
 * OpenAPI spec version: v3.1.1
 * Contact: ServiceDesk@openbanking.org.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace FinnovationLabs.OpenBanking.Library.Connector.ObModel.PaymentInitiation.V3p1p1.Model
{
    /// <summary>
    /// OBWriteDataFileResponse2
    /// </summary>
    [DataContract]
    public partial class OBWriteDataFileResponse2 :  IEquatable<OBWriteDataFileResponse2>, IValidatableObject
    {
        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name="Status", EmitDefaultValue=false)]
        public OBExternalStatus1Code Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="OBWriteDataFileResponse2" /> class.
        /// </summary>
        [JsonConstructor]
        protected OBWriteDataFileResponse2() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="OBWriteDataFileResponse2" /> class.
        /// </summary>
        /// <param name="filePaymentId">OB: Unique identification as assigned by the ASPSP to uniquely identify the file payment resource. (required).</param>
        /// <param name="consentId">OB: Unique identification as assigned by the ASPSP to uniquely identify the consent resource. (required).</param>
        /// <param name="creationDateTime">Date and time at which the message was created. All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00 (required).</param>
        /// <param name="status">status (required).</param>
        /// <param name="statusUpdateDateTime">Date and time at which the resource status was updated. All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00 (required).</param>
        /// <param name="charges">Set of elements used to provide details of a charge for the payment initiation..</param>
        /// <param name="initiation">initiation (required).</param>
        /// <param name="multiAuthorisation">multiAuthorisation.</param>
        public OBWriteDataFileResponse2(string filePaymentId = default(string), string consentId = default(string), DateTime? creationDateTime = default(DateTime?), OBExternalStatus1Code status = default(OBExternalStatus1Code), DateTime? statusUpdateDateTime = default(DateTime?), List<OBCharge2> charges = default(List<OBCharge2>), OBFile2 initiation = default(OBFile2), OBMultiAuthorisation1 multiAuthorisation = default(OBMultiAuthorisation1))
        {
            // to ensure "filePaymentId" is required (not null)
            if (filePaymentId == null)
            {
                throw new InvalidDataException("filePaymentId is a required property for OBWriteDataFileResponse2 and cannot be null");
            }
            else
            {
                this.FilePaymentId = filePaymentId;
            }
            // to ensure "consentId" is required (not null)
            if (consentId == null)
            {
                throw new InvalidDataException("consentId is a required property for OBWriteDataFileResponse2 and cannot be null");
            }
            else
            {
                this.ConsentId = consentId;
            }
            // to ensure "creationDateTime" is required (not null)
            if (creationDateTime == null)
            {
                throw new InvalidDataException("creationDateTime is a required property for OBWriteDataFileResponse2 and cannot be null");
            }
            else
            {
                this.CreationDateTime = creationDateTime;
            }
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new InvalidDataException("status is a required property for OBWriteDataFileResponse2 and cannot be null");
            }
            else
            {
                this.Status = status;
            }
            // to ensure "statusUpdateDateTime" is required (not null)
            if (statusUpdateDateTime == null)
            {
                throw new InvalidDataException("statusUpdateDateTime is a required property for OBWriteDataFileResponse2 and cannot be null");
            }
            else
            {
                this.StatusUpdateDateTime = statusUpdateDateTime;
            }
            // to ensure "initiation" is required (not null)
            if (initiation == null)
            {
                throw new InvalidDataException("initiation is a required property for OBWriteDataFileResponse2 and cannot be null");
            }
            else
            {
                this.Initiation = initiation;
            }
            this.Charges = charges;
            this.MultiAuthorisation = multiAuthorisation;
        }
        
        /// <summary>
        /// OB: Unique identification as assigned by the ASPSP to uniquely identify the file payment resource.
        /// </summary>
        /// <value>OB: Unique identification as assigned by the ASPSP to uniquely identify the file payment resource.</value>
        [DataMember(Name="FilePaymentId", EmitDefaultValue=false)]
        public string FilePaymentId { get; set; }

        /// <summary>
        /// OB: Unique identification as assigned by the ASPSP to uniquely identify the consent resource.
        /// </summary>
        /// <value>OB: Unique identification as assigned by the ASPSP to uniquely identify the consent resource.</value>
        [DataMember(Name="ConsentId", EmitDefaultValue=false)]
        public string ConsentId { get; set; }

        /// <summary>
        /// Date and time at which the message was created. All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
        /// </summary>
        /// <value>Date and time at which the message was created. All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00</value>
        [DataMember(Name="CreationDateTime", EmitDefaultValue=false)]
        public DateTime? CreationDateTime { get; set; }


        /// <summary>
        /// Date and time at which the resource status was updated. All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
        /// </summary>
        /// <value>Date and time at which the resource status was updated. All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00</value>
        [DataMember(Name="StatusUpdateDateTime", EmitDefaultValue=false)]
        public DateTime? StatusUpdateDateTime { get; set; }

        /// <summary>
        /// Set of elements used to provide details of a charge for the payment initiation.
        /// </summary>
        /// <value>Set of elements used to provide details of a charge for the payment initiation.</value>
        [DataMember(Name="Charges", EmitDefaultValue=false)]
        public List<OBCharge2> Charges { get; set; }

        /// <summary>
        /// Gets or Sets Initiation
        /// </summary>
        [DataMember(Name="Initiation", EmitDefaultValue=false)]
        public OBFile2 Initiation { get; set; }

        /// <summary>
        /// Gets or Sets MultiAuthorisation
        /// </summary>
        [DataMember(Name="MultiAuthorisation", EmitDefaultValue=false)]
        public OBMultiAuthorisation1 MultiAuthorisation { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class OBWriteDataFileResponse2 {\n");
            sb.Append("  FilePaymentId: ").Append(FilePaymentId).Append("\n");
            sb.Append("  ConsentId: ").Append(ConsentId).Append("\n");
            sb.Append("  CreationDateTime: ").Append(CreationDateTime).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  StatusUpdateDateTime: ").Append(StatusUpdateDateTime).Append("\n");
            sb.Append("  Charges: ").Append(Charges).Append("\n");
            sb.Append("  Initiation: ").Append(Initiation).Append("\n");
            sb.Append("  MultiAuthorisation: ").Append(MultiAuthorisation).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as OBWriteDataFileResponse2);
        }

        /// <summary>
        /// Returns true if OBWriteDataFileResponse2 instances are equal
        /// </summary>
        /// <param name="input">Instance of OBWriteDataFileResponse2 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OBWriteDataFileResponse2 input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.FilePaymentId == input.FilePaymentId ||
                    (this.FilePaymentId != null &&
                    this.FilePaymentId.Equals(input.FilePaymentId))
                ) && 
                (
                    this.ConsentId == input.ConsentId ||
                    (this.ConsentId != null &&
                    this.ConsentId.Equals(input.ConsentId))
                ) && 
                (
                    this.CreationDateTime == input.CreationDateTime ||
                    (this.CreationDateTime != null &&
                    this.CreationDateTime.Equals(input.CreationDateTime))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                ) && 
                (
                    this.StatusUpdateDateTime == input.StatusUpdateDateTime ||
                    (this.StatusUpdateDateTime != null &&
                    this.StatusUpdateDateTime.Equals(input.StatusUpdateDateTime))
                ) && 
                (
                    this.Charges == input.Charges ||
                    this.Charges != null &&
                    this.Charges.SequenceEqual(input.Charges)
                ) && 
                (
                    this.Initiation == input.Initiation ||
                    (this.Initiation != null &&
                    this.Initiation.Equals(input.Initiation))
                ) && 
                (
                    this.MultiAuthorisation == input.MultiAuthorisation ||
                    (this.MultiAuthorisation != null &&
                    this.MultiAuthorisation.Equals(input.MultiAuthorisation))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.FilePaymentId != null)
                    hashCode = hashCode * 59 + this.FilePaymentId.GetHashCode();
                if (this.ConsentId != null)
                    hashCode = hashCode * 59 + this.ConsentId.GetHashCode();
                if (this.CreationDateTime != null)
                    hashCode = hashCode * 59 + this.CreationDateTime.GetHashCode();
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                if (this.StatusUpdateDateTime != null)
                    hashCode = hashCode * 59 + this.StatusUpdateDateTime.GetHashCode();
                if (this.Charges != null)
                    hashCode = hashCode * 59 + this.Charges.GetHashCode();
                if (this.Initiation != null)
                    hashCode = hashCode * 59 + this.Initiation.GetHashCode();
                if (this.MultiAuthorisation != null)
                    hashCode = hashCode * 59 + this.MultiAuthorisation.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // FilePaymentId (string) maxLength
            if(this.FilePaymentId != null && this.FilePaymentId.Length > 40)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for FilePaymentId, length must be less than 40.", new [] { "FilePaymentId" });
            }

            // FilePaymentId (string) minLength
            if(this.FilePaymentId != null && this.FilePaymentId.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for FilePaymentId, length must be greater than 1.", new [] { "FilePaymentId" });
            }

            // ConsentId (string) maxLength
            if(this.ConsentId != null && this.ConsentId.Length > 128)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ConsentId, length must be less than 128.", new [] { "ConsentId" });
            }

            // ConsentId (string) minLength
            if(this.ConsentId != null && this.ConsentId.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ConsentId, length must be greater than 1.", new [] { "ConsentId" });
            }

            yield break;
        }
    }

}
