// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace FinnovationLabs.OpenBanking.Library.BankApiModels.UkObRw.V3p1p10.Aisp.Models
{
    /// <summary>
    ///     Request object OBReadConsent1 from UK Open Banking Read-Write Account and Transaction API spec
    ///     <a
    ///         href="https://github.com/OpenBankingUK/read-write-api-specs/blob/v3.1.10r5/dist/openapi/account-info-openapi.yaml" />
    ///     v3.1.10r5 <a />. Open Banking Connector will automatically
    ///     translate <i>from</i> this to an older format for banks supporting an earlier spec version.
    /// </summary>
    [TargetApiEquivalent(typeof(V3p1p7.Aisp.Models.OBReadConsent1))]
    public partial class OBReadConsent1
    {
        /// <summary> Initializes a new instance of OBReadConsent1. </summary>
        /// <param name="data"></param>
        /// <param name="risk"> Any object. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="data"/> or <paramref name="risk"/> is null. </exception>
        public OBReadConsent1(OBReadConsent1Data data, object risk)
        {
            if (data == null)
            {
                throw new ArgumentNullException(nameof(data));
            }
            if (risk == null)
            {
                throw new ArgumentNullException(nameof(risk));
            }

            Data = data;
            Risk = risk;
        }

        /// <summary> Gets the data. </summary>
        public OBReadConsent1Data Data { get; }
        /// <summary> Any object. </summary>
        public object Risk { get; }
    }
}
